// <auto-generated />
namespace LibraryManagementProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class books : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(books));
        
        string IMigrationMetadata.Id
        {
            get { return "202306252347472_books"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
